---
- name: Deploy Docker Compose Services
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml

  tasks:
      - name: Copy compose file
        copy:
          src: ../files/docker-compose.yml
          dest: /opt/minio/docker-compose.yml

      - name: Copy environment file
        template:
          src: ../templates/compose.env.j2
          dest: /opt/minio/.env
          mode: '0644'

      - name: Start all services
        community.docker.docker_compose_v2:
          project_src: /opt/minio
          state: present
          recreate: always