---
- name: Deploy MinIO, MongoDB, Zot and Nginx
  hosts: all
  become: true

  tasks:

    - name: Create data directory
      file:
        path: /data/minio
        state: directory
        mode: "0755"

    - name: Create docker-compose directory
      file:
        path: /opt/minio
        state: directory

    - name: Remove existing zot directory if it exists
      file:
        path: /opt/zot
        state: absent

    - name: Create zot config directory
      file:
        path: /opt/zot
        state: directory
        mode: '0755'

    - name: Copy Zot configuration
      copy:
        src: ../files/config.json
        dest: /opt/zot
        mode: '0644'

    - name: Create zot certs directory
      file:
        path: /opt/zot/certs
        state: directory
        mode: '0755'

    - name: Copy compose file
      copy:
        src: ../files/docker-compose.yml
        dest: /opt/minio/docker-compose.yml
        mode: '0644'

    - name: Create registry storage
      file:
        path: /opt/storage
        state: directory
        mode: '0755'

    - name: Create nginx config directory
      file:
        path: /opt/nginx/conf.d
        state: directory
        mode: '0755'

    - name: Copy Nginx configuration with AI endpoint
      copy:
        src: ../files/nginx/conf.d/default.conf
        dest: /opt/nginx/conf.d/default.conf
        mode: '0644'

    - name: Start services
      community.docker.docker_compose_v2:
        project_src: /opt/minio
        state: present