[k3s_master]
k3s-master-01 ansible_host=<MASTER_IP> ansible_user=ubuntu

[k3s_workers]
k3s-worker-01 ansible_host=<WORKER_IP_1> ansible_user=ubuntu
k3s-worker-02 ansible_host=<WORKER_IP_2> ansible_user=ubuntu

[all:vars]
admin_user=ubuntu
k3s_tls_san=<MASTER_IP>